name: Deploy to A.D.S. Games

on:
  push:
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - run: yarn --frozen-lockfile

      - run: yarn build

      - uses: adsgames/deploy-to-adsgames@v1.1.0
        with:
          project-id: brickbreaker
          build-dir: dist
          platform: WEB
          bucket-access-key: ${{ secrets.LINODE_BUCKET_ACCESS_KEY }}
          bucket-secret-key: ${{ secrets.LINODE_BUCKET_SECRET_KEY }}
          api-key: ${{ secrets.ADSGAMES_API_KEY }}
