name: Build Game

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn --frozen-lockfile
      
    - name: Build project
      run: yarn build
    
    - name: Zip build
      run: cd dist && ls && zip -r ./build.zip *

    - name: Persist build.zip
      uses: actions/upload-artifact@v1
      with:
        name: build-zip
        path: "./dist/build.zip"
